"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    title: "What is a rebate and where does it come from?",
    body: "A rebate is a portion of the trading fee (spread/commission) that your broker returns through Zentrix. This money comes from your actual trading volume — not from any other source.",
  },
  {
    title: "Is KYC required?",
    body: "Yes. KYC is mandatory to withdraw funds, in order to comply with AML regulations and protect your account. The process involves uploading a government-issued ID and a selfie — typically processed within a few business hours.",
  },
  {
    title: "What is the on-chain Pool? Is my money safe?",
    body: "The Pool is a BEP20 smart contract that holds rebate liquidity. Funds enter the Pool only after broker payouts have been received by treasury and verified through 3-way reconciliation. You can check the Pool balance and full claim history directly on BSCScan.",
  },
  {
    title: "How long does it take to receive my rebates?",
    body: "Rebates are recorded as your trading volume comes in. After each settlement period (typically weekly or monthly depending on the broker), rebates are confirmed and opened for claiming. You can claim at any time after that.",
  },
  {
    title: "Is Zentrix an MLM scheme?",
    body: "No. Referral commissions come from the actual trading fees generated by people you refer — not from selling participation packages or requiring deposits. Zentrix does not require you to purchase anything to participate.",
  },
  {
    title: "Can I connect multiple brokers?",
    body: "Yes. You can link multiple broker accounts under a single Zentrix account. Rebates from all brokers are consolidated in one place.",
  },
];

export function FAQSection() {
  const [openIndex, setOpenIndex] = useState(0);

  return (
    <section id="faq" className="relative py-20 overflow-hidden scroll-mt-24">
      <div className="max-w-[826px] mx-auto px-6">
        <motion.h2
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5 }}
          className="text-[36px] font-bold mb-4 text-center"
        >
          Frequently asked questions
        </motion.h2>
        <p className="text-center text-white/50 text-sm mb-12 max-w-lg mx-auto">
          Everything you need to know about rebates, fees, and how Zentrix stays transparent.
        </p>

        <div className="flex flex-col gap-3">
          {faqs.map((faq, i) => (
            <motion.div
              key={faq.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="rounded-xl bg-black/40 border border-white/5 overflow-hidden"
            >
              <button
                type="button"
                onClick={() => setOpenIndex(openIndex === i ? -1 : i)}
                className="w-full flex items-center justify-between p-6 text-left hover:bg-white/5 transition-colors"
              >
                <span className="text-base font-medium pr-4">{faq.title}</span>
                <ChevronDown
                  className={`w-5 h-5 shrink-0 transition-transform duration-300 ${
                    openIndex === i ? "rotate-180" : ""
                  }`}
                />
              </button>
              <AnimatePresence>
                {openIndex === i && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.2 }}
                    className="overflow-hidden"
                  >
                    <div className="px-6 pb-6 text-sm text-white/60 leading-relaxed">{faq.body}</div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
